[data]
# Path to the CSV file to process
input_csv_path = "data/input/companies.csv"

# Column name in the CSV to use for API queries
target_column = "Cuenta"

[model]
model_name = "sonar-pro"
temperature = 0.1

[output]
# Output configuration
output_csv_path = "data/output/results.json"

[debug]
debug_mode = false