[data]
# Path to the CSV file to process
input_csv_path = "data/input/companies.csv"

# Column name in the CSV to use for API queries
[target_column]
col_name = "Cuenta"

[model]
model_name = "sonar-pro"
temperature = 0.1

[output]
# Output configuration
output_csv_path = "data/output/results.json"

[chain_of_responsability]
model_chain = ["gemini", "perplexity", "fallback"]